### PR TITLE
Update ExprTk

### PR DESCRIPTION
**Pull request by ArashPartow**
This update adds:

1. Runtime checks to expressions when being evaluated
2. Stackoverflow protections during both compilation and evaluation
3. Various evaluation performance improvements
4. Code clean-up in prep for rebasing to C++17

### CODE REVIEW

**Comment by Nicogene** [comment]
Hi @ArashPartow!

Thanks for submitting the PR, could you please fill up the body of the PR explaining the rationale of your changes?
Thanks!

**Comment by ArashPartow** [comment]
@Nicogene  it seems the release/debug workflows are stuck, anything I can do at my end?

**Comment by traversaro** [comment]
> @Nicogene  it seems the release/debug workflows are stuck, anything I can do at my end?

Apparently it needed an approval to run, now it should be work fine.

**Review by Nicogene — APPROVED** [review]

**Comment by Nicogene** [comment]
Merged, thanks!

**Pull request merged**
